
spring:
  url:
    base: http://localhost:8080
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        ddl-auto: update
        hbm2ddl:
          auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

logging.level:
  org.hibernate.SQL: debug # logger를 통해 하이버네이트 실행 SQL을 남긴다.
  org.hibernate.type: trace # SQL 실행 파라미터를 로그로 남긴다.



upload:
  path:
    post: E:\Spring\bh-back\src\images\post
    profile: E:\Spring\bh-back\src\images\profile


#  h2 설정
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create # 애플리케이션 실행 시점에 테이블을 drop 하고, 다시 생성
#    properties:
#      hibernate:
#        format_sql: true