spring:
  datasource:
    url: jdbc:mysql://35.187.204.164:3306/web_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: hansol2
    password: twntyone21@
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        ddl-auto: update
        hbm2ddl:
          auto: create
    show-sql: true
  url:
    base: http://35.227.155.59:8080