spring:
  jwt:
    secret: {AccessToken}

social:
  kakao:
    client-id: 775ecf215c5d89163efd737a3ded33a4
    redirect: /oauth/kakao/callback

    url:
      login: https://kauth.kakao.com/oauth/authorize
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink